steps:
      - uses: actions/checkout@v6

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=8&theme=radical
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Pin - Anchor Project
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          # Replace 'Anchor' with the exact name of your repository
          options: username=${{ github.repository_owner }}&repo=Anchor&theme=radical
          path: profile/pin-anchor.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Pin - LegacyQuest
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          # Replace 'LegacyQuest' with the exact name of your repository
          options: username=${{ github.repository_owner }}&repo=LegacyQuest&theme=radical
          path: profile/pin-legacy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Focus on projects over stats" || exit 0
          git push
